### ISSUE TITLE
Even heroku branch not working.

### ISSUE THREAD

**Issue by Devansh1511** [anasty17/mirror-leech-telegram-bot#648] opened 2022-06-04 23:00 UTC
I made no changes in the repo. Just forked it and everything is in my config.env

Some of us are getting `/venv/bin/python3: No module named bot`

**Comment by sanwar-hosen** [comment] 2022-06-05 00:25
++same here

**Comment by arakurumi** [comment] 2022-06-05 01:29
I just deployed and didn't have that problem, try uploading private files (token.pickle, accounts folder) on heroku branch not on master branch

**Comment by AkashWasim** [comment] 2022-06-05 02:24
> I just deployed and didn't have that problem, try uploading private files (token.pickle, accounts folder) on heroku branch not on master branch

i did that..i had a bot before when heroku died i stopped using it. 
yesterday i made a new fork then uploaded my crediential,account folders, token and token_sa in heroku branch. set secrets and config. but somehow my bot doesnt get deployed on heroku. everytime i deploy it, it fails

**Comment by erickyun** [comment] 2022-06-05 08:38
this is duplicate of #646 To avoid any clutter You should close this issue and follow the solution from there.

**Closed** 2022-06-05 09:13 UTC
