### ISSUE TITLE
No module named bot [ERROR]

### ISSUE THREAD

**Issue by sanwar-hosen** [anasty17/mirror-leech-telegram-bot#649] opened 2022-06-05 00:23 UTC
2022-06-05T00:19:56.859128+00:00 heroku[web.1]: State changed from crashed to starting
2022-06-05T00:20:13.663357+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2022-06-05T00:20:14.603909+00:00 app[web.1]: /venv/bin/python3: No module named bot
2022-06-05T00:20:14.738576+00:00 heroku[web.1]: Process exited with status 1
2022-06-05T00:20:14.834301+00:00 heroku[web.1]: State changed from starting to crashed
2022-06-05T00:20:52.180216+00:00 heroku[web.1]: State changed from crashed to starting
2022-06-05T00:21:09.057139+00:00 heroku[web.1]: Starting process with command `bash start.sh`
2022-06-05T00:21:09.942335+00:00 app[web.1]: **/venv/bin/python3: No module named bot**
2022-06-05T00:21:10.109311+00:00 heroku[web.1]: Process exited with status 1

**Comment by erickyun** [comment] 2022-06-05 08:42
> 2022-06-05T00:19:56.859128+00:00 heroku[web.1]: State changed from crashed to starting 2022-06-05T00:20:13.663357+00:00 heroku[web.1]: Starting process with command `bash start.sh` 2022-06-05T00:20:14.603909+00:00 app[web.1]: /venv/bin/python3: No module named bot 2022-06-05T00:20:14.738576+00:00 heroku[web.1]: Process exited with status 1 2022-06-05T00:20:14.834301+00:00 heroku[web.1]: State changed from starting to crashed 2022-06-05T00:20:52.180216+00:00 heroku[web.1]: State changed from crashed to starting 2022-06-05T00:21:09.057139+00:00 heroku[web.1]: Starting process with command `bash start.sh` 2022-06-05T00:21:09.942335+00:00 app[web.1]: **/venv/bin/python3: No module named bot** 2022-06-05T00:21:10.109311+00:00 heroku[web.1]: Process exited with status 1

this is duplicate of #646 To avoid any clutter You should close this issue and follow the solution from there.

**Closed** 2022-06-05 09:13 UTC
